version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # build the application image
     - run: docker build --rm=false -t kylesykes/genericwebapp:$CIRCLE_SHA1 genericwebapp/.

     # deploy the image
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker push kylesykes/genericwebapp 